/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifms.tcc.telas;

import br.edu.ifms.tcc.classes.Conteudo3;
import br.edu.ifms.tcc.classes.Usuario;
import br.edu.ifms.tcc.telas.Login;
import br.edu.ifms.tcc.telas.MenuExer;
import br.edu.ifms.tcc.conexaoDAO1.Cont3DAO;
import static java.awt.SystemColor.text;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.UIManager;

/**
 *
 * @author Chrigor
 */
public class Cont3_exercicios extends javax.swing.JFrame {
    

    boolean ver = false;
    /**
     * Creates new form Nivel1
     */
    public Cont3_exercicios() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JRB1 = new javax.swing.JRadioButton();
        JRB2 = new javax.swing.JRadioButton();
        JRB3 = new javax.swing.JRadioButton();
        JRB4 = new javax.swing.JRadioButton();
        JRB5 = new javax.swing.JRadioButton();
        JBproximo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JLnum = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        calcule = new javax.swing.JTextArea();
        JBproximo1 = new javax.swing.JButton();
        JLimagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        buttonGroup1.add(JRB1);
        JRB1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JRB1.setText("I-IV-V. ");
        JRB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(JRB2);
        JRB2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JRB2.setText("II-IV-VI.");

        buttonGroup1.add(JRB3);
        JRB3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JRB3.setText("I-II-V.");
        JRB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(JRB4);
        JRB4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JRB4.setText("II-IV-VI.");

        buttonGroup1.add(JRB5);
        JRB5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JRB5.setText("I-III-V.");

        JBproximo.setBackground(new java.awt.Color(51, 204, 0));
        JBproximo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JBproximo.setText("Próximo");
        JBproximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBproximoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Exercício");

        JLnum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JLnum.setText("61");

        jScrollPane1.setBackground(java.awt.SystemColor.controlHighlight);

        calcule.setEditable(false);
        calcule.setBackground(new java.awt.Color(240, 240, 240));
        calcule.setColumns(20);
        calcule.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        calcule.setLineWrap(true);
        calcule.setRows(9);
        calcule.setTabSize(10);
        calcule.setText("Verifique se as afirmações são verdadeiras ou falsas.\n\nI – Todo número natural é inteiro?\nII – Todo número inteiro é natural?\nIII – Todo número inteiro é racional?\nIV – Todo número irracional é racional?\nV – Todo número inteiro é real?\nVI – Todo número é real?\nMarque a opção que contenha apenas as afirmações verdadeiras:");
        calcule.setToolTipText("");
        calcule.setAutoscrolls(false);
        calcule.setBorder(null);
        calcule.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jScrollPane1.setViewportView(calcule);

        JBproximo1.setBackground(new java.awt.Color(51, 204, 0));
        JBproximo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JBproximo1.setText("Parar");
        JBproximo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBproximo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLnum)
                        .addGap(0, 1166, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JRB1)
                            .addComponent(JRB2)
                            .addComponent(JRB3)
                            .addComponent(JRB4)
                            .addComponent(JRB5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JLimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(562, 562, 562)
                .addComponent(JBproximo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBproximo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JLnum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(JRB1)
                                .addGap(18, 18, 18)
                                .addComponent(JRB2)
                                .addGap(18, 18, 18)
                                .addComponent(JRB3)
                                .addGap(18, 18, 18)
                                .addComponent(JRB4)
                                .addGap(18, 18, 18)
                                .addComponent(JRB5)))
                        .addContainerGap(72, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBproximo1)
                            .addComponent(JBproximo))
                        .addGap(25, 25, 25))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private boolean prim = true;
    Conteudo3 meto = new Conteudo3();
    String erro = "61";
    private void JBproximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBproximoActionPerformed
        if(JRB1.isSelected() || JRB2.isSelected() || JRB3.isSelected() || JRB4.isSelected() || JRB5.isSelected()){
            if(prim && JRB5.isSelected()){
                meto.setPrimquest(1);
                prim = false;
                erro = "";
            } 
            
        if(JRB1.isSelected() && "1".equals(meto.getResult())){
            meto.setResult("correta");
        } else if(JRB2.isSelected() && "2".equals(meto.getResult())){
            meto.setResult("correta");
        } else if(JRB3.isSelected() && "3".equals(meto.getResult())){
            meto.setResult("correta");
        } else if(JRB4.isSelected() && "4".equals(meto.getResult())){
            meto.setResult("correta");
        } else if(JRB5.isSelected() && "5".equals(meto.getResult())){
            meto.setResult("correta");
        } else if(meto.getNumquestao() !=0){erro = erro + "," + String.valueOf(meto.getNumquestao());}
        Cont3DAO.Contador(meto);
        if(meto.getBotaoprox() == "Finalizar"){
            if(erro == "61"){
                erro = "Parabêns, Você acertou todas as questões!!!";
            }
            meto.setErros(erro);
            erro = "61";
            //Cont1DAO.Historico(meto);
            JOptionPane.showMessageDialog(null, "Parabêns você respondeu todas as questões do conteúdo 3, Clique em OK para ver seus resultados!");
            Barra_de_Progresso bar = new Barra_de_Progresso();
            bar.setVisible(true);
            this.dispose();
        }
        Cont3DAO.receberquestao(meto);
        calcule.setText(meto.getExercicio());
        JRB1.setText(meto.getAlt1());
        JRB2.setText(meto.getAlt2());
        JRB3.setText(meto.getAlt3());
        JRB4.setText(meto.getAlt4());
        JRB5.setText(meto.getAlt5());
        JBproximo.setText(meto.getBotaoprox());
        JLnum.setText(String.valueOf(meto.getNumquestao()));
        meto.setPrimquest(0);
        JRB1.setSelected(false);
        JRB2.setSelected(false);
        JRB3.setSelected(false);
        JRB4.setSelected(false);
        JRB5.setSelected(false);
        if (meto.getNumquestao() == 64) {
                ImageIcon img = new ImageIcon(getClass().getResource("/br/edu/ifms/tcc/imagens/Cont3_64.png"));
                JLimagem.setIcon(img);
        } else if (meto.getNumquestao() == 78) {
                ImageIcon img = new ImageIcon(getClass().getResource("/br/edu/ifms/tcc/imagens/Cont3_78.png"));
                JLimagem.setIcon(img);
        } else if (meto.getNumquestao() == 81) {
                ImageIcon img = new ImageIcon(getClass().getResource("/br/edu/ifms/tcc/imagens/Cont3_81.png"));
                JLimagem.setIcon(img);
        } else if (meto.getNumquestao() == 82) {
                ImageIcon img = new ImageIcon(getClass().getResource("/br/edu/ifms/tcc/imagens/Cont3_82.png"));
                JLimagem.setIcon(img);
        } else { ImageIcon img = new ImageIcon(getClass().getResource(""));
            JLimagem.setIcon(img);}
        } else {JOptionPane.showMessageDialog(null, "Selecione uma Alternativa");}
    }//GEN-LAST:event_JBproximoActionPerformed

    private void JRB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRB3ActionPerformed

    private void JRB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRB1ActionPerformed

    private void JBproximo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBproximo1ActionPerformed
        MenuExer janela = new MenuExer();
        janela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBproximo1ActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cont3_exercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cont3_exercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cont3_exercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cont3_exercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cont3_exercicios().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBproximo;
    private javax.swing.JButton JBproximo1;
    private javax.swing.JLabel JLimagem;
    private javax.swing.JLabel JLnum;
    private javax.swing.JRadioButton JRB1;
    private javax.swing.JRadioButton JRB2;
    private javax.swing.JRadioButton JRB3;
    private javax.swing.JRadioButton JRB4;
    private javax.swing.JRadioButton JRB5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea calcule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
