/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifms.tcc.telas;

import br.edu.ifms.tcc.classes.Tabela;
import br.edu.ifms.tcc.classes.Usuario;
import br.edu.ifms.tcc.conexaoDAO1.Conexao;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Chrigor
 */
public class Listagem_Ponto extends javax.swing.JFrame {
Usuario usua = new Usuario();
    /**
     * Creates new form Listagem
     */
    public Listagem_Ponto() {
        initComponents();
        PontoTabela("SELECT*FROM HistoricoPontuacao WHERE nome_aluno ="+ usua.nome_logado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTListagem = new javax.swing.JTable();
        JBVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        JTListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(JTListagem);

        JBVoltar.setBackground(new java.awt.Color(0, 204, 51));
        JBVoltar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JBVoltar.setText("Voltar Menu");
        JBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JBVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JBVoltar)
                .addGap(82, 82, 82)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVoltarActionPerformed
       TelaInicial janela = new TelaInicial();
       janela.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_JBVoltarActionPerformed

    public void PontoTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Nome","Pontuação 1","Pontuação 2","Pontuação 3","Pontuação 4","Questões Erradas"};
        
        String sql = "SELECT*FROM HistoricoPontuacao WHERE nome_aluno = ?";
                
            try{
            PreparedStatement pstm = new Conexao().fazerConexao().prepareStatement(sql);
            pstm.setObject(1, usua.nome_logado);
            ResultSet rs = pstm.executeQuery();
            while(rs.next()){
                String nome = rs.getString("nome_aluno");
                int ex1 = rs.getInt("pont1");
                int ex2 = rs.getInt("pont2");
                int ex3 = rs.getInt("pont3");
                int ex4 = rs.getInt("pont4");
                String questerr = rs.getString("questoes_erradas");
                dados.add(new Object[]{nome, ex1, ex2, ex3, ex4, questerr});
            }
            pstm.close();      
        }catch(SQLException ex){
            System.out.println("Erro");
            System.out.println(ex.getMessage());
        }
           
        
        Tabela tab = new Tabela(dados, colunas);
        
        JTListagem.setModel(tab);
        JTListagem.getColumnModel().getColumn(0).setPreferredWidth(450);
        JTListagem.getColumnModel().getColumn(0).setResizable(false);
        JTListagem.getColumnModel().getColumn(1).setPreferredWidth(91);
        JTListagem.getColumnModel().getColumn(1).setResizable(false);
        JTListagem.getColumnModel().getColumn(2).setPreferredWidth(91);
        JTListagem.getColumnModel().getColumn(2).setResizable(false);
        JTListagem.getColumnModel().getColumn(3).setPreferredWidth(91);
        JTListagem.getColumnModel().getColumn(3).setResizable(false);
        JTListagem.getColumnModel().getColumn(4).setPreferredWidth(91);
        JTListagem.getColumnModel().getColumn(4).setResizable(false);
        JTListagem.getColumnModel().getColumn(5).setPreferredWidth(451);
        JTListagem.getColumnModel().getColumn(5).setResizable(false);
        JTListagem.setAutoResizeMode(JTListagem.AUTO_RESIZE_OFF);
        JTListagem.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listagem_Ponto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listagem_Ponto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listagem_Ponto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listagem_Ponto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listagem_Ponto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBVoltar;
    private javax.swing.JTable JTListagem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
