/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifms.tcc.telas;

import br.edu.ifms.tcc.classes.Usuario;
import br.edu.ifms.tcc.conexaoDAO1.UsuarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Chrigor
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Loguin
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPFundo = new javax.swing.JPanel();
        JLImagemInicial = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JLLogin = new javax.swing.JLabel();
        JBCancelar = new javax.swing.JButton();
        JBLogar = new javax.swing.JButton();
        JLCriarConta = new javax.swing.JLabel();
        JLEsqueceuConta = new javax.swing.JLabel();
        JTFLogin = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        JPFundo.setBackground(new java.awt.Color(0, 204, 204));
        JPFundo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JLImagemInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifms/tcc/imagens/login.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JLLogin.setFont(new java.awt.Font("Swis721 Cn BT", 1, 36)); // NOI18N
        JLLogin.setText("Login");

        JBCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JBCancelar.setText("Sair");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        JBLogar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JBLogar.setText("Logar");
        JBLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLogarActionPerformed(evt);
            }
        });

        JLCriarConta.setBackground(new java.awt.Color(0, 0, 255));
        JLCriarConta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JLCriarConta.setForeground(new java.awt.Color(0, 0, 204));
        JLCriarConta.setText("Criar conta");
        JLCriarConta.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JLCriarContaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        JLCriarConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLCriarContaMouseClicked(evt);
            }
        });

        JLEsqueceuConta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JLEsqueceuConta.setForeground(new java.awt.Color(0, 0, 204));
        JLEsqueceuConta.setText("Esqueceu a Conta?");
        JLEsqueceuConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLEsqueceuContaMouseClicked(evt);
            }
        });

        JTFLogin.setToolTipText("Usuario");
        JTFLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Excluir usuario");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(JLLogin)
                .addGap(0, 99, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JBCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBLogar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLEsqueceuConta)
                            .addComponent(JLCriarConta))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTFLogin)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(JLLogin)
                .addGap(18, 18, 18)
                .addComponent(JTFLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(JLCriarConta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLEsqueceuConta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBCancelar)
                            .addComponent(JBLogar))
                        .addContainerGap())))
        );

        JTFLogin.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout JPFundoLayout = new javax.swing.GroupLayout(JPFundo);
        JPFundo.setLayout(JPFundoLayout);
        JPFundoLayout.setHorizontalGroup(
            JPFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPFundoLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(JPFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLImagemInicial))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        JPFundoLayout.setVerticalGroup(
            JPFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPFundoLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(JLImagemInicial)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JLCriarContaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JLCriarContaAncestorAdded
      
    }//GEN-LAST:event_JLCriarContaAncestorAdded

    private void JBLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLogarActionPerformed
        String nome_aluno = JTFLogin.getText();
        Usuario usuario = UsuarioDAO.verificarUsu(nome_aluno);
        if(usuario != null){
            TelaInicial janela = new TelaInicial();
            janela.setVisible(true);
            this.dispose();
            usuario.nome_logado = nome_aluno;
        }
        else{
            JOptionPane.showMessageDialog(null, "Usuario não existe !");
        }
        
    }//GEN-LAST:event_JBLogarActionPerformed

    private void JLCriarContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLCriarContaMouseClicked
        Cadastrar janela = new Cadastrar();
        janela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JLCriarContaMouseClicked

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JLEsqueceuContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLEsqueceuContaMouseClicked
        UsuariosExistentes janela = new  UsuariosExistentes();
        janela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JLEsqueceuContaMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBLogar;
    private javax.swing.JLabel JLCriarConta;
    private javax.swing.JLabel JLEsqueceuConta;
    private javax.swing.JLabel JLImagemInicial;
    private javax.swing.JLabel JLLogin;
    private javax.swing.JPanel JPFundo;
    private javax.swing.JFormattedTextField JTFLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
