/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifms.tcc.telas;

import br.edu.ifms.tcc.classes.Conteudo1;
import br.edu.ifms.tcc.classes.Usuario;
import br.edu.ifms.tcc.telas.Login;
import br.edu.ifms.tcc.telas.MenuExer;
import br.edu.ifms.tcc.conexaoDAO1.Cont1DAO;
import br.edu.ifms.tcc.conexaoDAO1.PesquisaDAO;
import static java.awt.SystemColor.text;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.UIManager;

/**
 *
 * @author Chrigor
 */
public class Pesquisa_Questao extends javax.swing.JFrame {

    static int recebnum;
    static String questao;
    static PesquisaDAO me = new PesquisaDAO();
    static Pesquisa_Questao pequi = new Pesquisa_Questao();
    
    
    public String getQuestao() {
        return questao;
    }

    public void setQuestao(String questao) {
        Pesquisa_Questao.questao = questao;
    }

    public static int getRecebnum() {
        return recebnum;
    }

    public static void setRecebnum(int recebnum) {
        Pesquisa_Questao.recebnum = recebnum;
    }

    /**
     * Creates new form Nivel1
     */
    public Pesquisa_Questao() {
        initComponents();
        Chamar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JBvoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JLnum = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        calcule = new javax.swing.JTextArea();
        Jlabelima = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        JBvoltar.setBackground(new java.awt.Color(51, 204, 0));
        JBvoltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JBvoltar.setText("Voltar");
        JBvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBvoltarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Exercício");

        JLnum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JLnum.setText("NUM");

        jScrollPane1.setBackground(java.awt.SystemColor.controlHighlight);

        calcule.setEditable(false);
        calcule.setBackground(new java.awt.Color(240, 240, 240));
        calcule.setColumns(20);
        calcule.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        calcule.setLineWrap(true);
        calcule.setRows(3);
        calcule.setTabSize(10);
        calcule.setText("NaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNaNa");
        calcule.setToolTipText("");
        calcule.setAutoscrolls(false);
        calcule.setBorder(null);
        calcule.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jScrollPane1.setViewportView(calcule);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JLnum)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Jlabelima, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(JBvoltar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(JLnum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(Jlabelima, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JBvoltar)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBvoltarActionPerformed
        MenuExer meex = new MenuExer();
        meex.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBvoltarActionPerformed
    
    public void Chamar(){
                if(recebnum == 1){
                    JLnum.setText(String.valueOf(recebnum));
                    calcule.setText("Calcule, 8456-6780:");
                } else if(recebnum == 31){
                    JLnum.setText(String.valueOf(recebnum));
                    calcule.setText("XYZ4 e X4YZ representam dois números inteiros de quatro algarismos. Se X4YZ excede XYZ4 em 288 unidades, então Z-Y é igual a:");
                } else if(recebnum == 61){
                    JLnum.setText(String.valueOf(recebnum));
                    calcule.setText("aqui!");
                } else if(recebnum == 91){
                    JLnum.setText(String.valueOf(recebnum));
                    calcule.setText("aqui!");
                } else if (recebnum <= 30) {
                    JLnum.setText(String.valueOf(recebnum));
                    recebnum = recebnum - 1;
                    me.PQ1(pequi);
                    calcule.setText(questao);
                } else if (recebnum <= 60) {
                    JLnum.setText(String.valueOf(recebnum));
                    recebnum = recebnum - 31;
                    me.PQ2(pequi);
                    calcule.setText(questao);
                } else if (recebnum <= 90) {
                    JLnum.setText(String.valueOf(recebnum));
                    recebnum = recebnum - 61;
                    me.PQ3(pequi);
                    calcule.setText(questao);
                } else if (recebnum <= 120) {
                    JLnum.setText(String.valueOf(recebnum));
                    recebnum = recebnum - 91;
                    me.PQ4(pequi);
                    calcule.setText(questao);
                }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesquisa_Questao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesquisa_Questao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesquisa_Questao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesquisa_Questao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesquisa_Questao().setVisible(true);
                JPanel panel = new JPanel();
                ImageIcon img = new ImageIcon("br.edu.ifms.tcc.imagens.rosto.png");
                JLabel labelima = new JLabel(img);
                panel.add(labelima);
                JTextArea textArea = new JTextArea(2, 20);
                textArea.setText("Calcule:        8456   -  6780:");
                textArea.setWrapStyleWord(true);
                textArea.setLineWrap(true);
                textArea.setOpaque(false);
                textArea.setEditable(false);
                textArea.setFocusable(false);
                textArea.setBackground(UIManager.getColor("Label.background"));
                textArea.setFont(UIManager.getFont("Label.font"));
                textArea.setBorder(UIManager.getBorder("Label.border"));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBvoltar;
    private static javax.swing.JLabel JLnum;
    private javax.swing.JLabel Jlabelima;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea calcule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
