/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifms.tcc.telas;

import br.edu.ifms.tcc.classes.Tabela;
import br.edu.ifms.tcc.classes.Usuario;
import br.edu.ifms.tcc.conexaoDAO1.Conexao;
import br.edu.ifms.tcc.conexaoDAO1.UsuarioDAO;
import java.awt.Dimension;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class UsuariosExistentes extends javax.swing.JFrame {

    Conexao conex = new Conexao();
    
    public UsuariosExistentes() {
        initComponents();
        preencherTabela("SELECT*FROM aluno ORDER BY id_aluno");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JSPUsuario = new javax.swing.JScrollPane();
        JTUsu_Exis = new javax.swing.JTable();
        JBVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(681, 479));

        JTUsu_Exis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JSPUsuario.setViewportView(JTUsu_Exis);

        JBVoltar.setBackground(new java.awt.Color(0, 204, 51));
        JBVoltar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JBVoltar.setText("Voltar");
        JBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(JBVoltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(JSPUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JBVoltar)
                .addGap(86, 86, 86)
                .addComponent(JSPUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVoltarActionPerformed
         Login janela = new Login();
         janela.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_JBVoltarActionPerformed

    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Id","Nome","Idade"};
        
        
        String sql = "SELECT * FROM Aluno";
  
        try{
            PreparedStatement pstm = new Conexao().fazerConexao().prepareStatement(sql);
            ResultSet rs = pstm.executeQuery();
            while(rs.next()){
                int id = rs.getInt("id_aluno");
                String nome_aluno = rs.getString("nome_aluno");
                int idade = rs.getInt("idade_aluno");
                dados.add(new Object[]{id, nome_aluno, idade});
            }
            pstm.execute();
            pstm.close();      
        }catch(SQLException ex){
            System.out.println("Erro");
            System.out.println(ex.getMessage());
        }
        
        Tabela tab = new Tabela(dados, colunas);
        
        JTUsu_Exis.setModel(tab);
        JTUsu_Exis.getColumnModel().getColumn(0).setPreferredWidth(90);
        JTUsu_Exis.getColumnModel().getColumn(0).setResizable(false);
        JTUsu_Exis.getColumnModel().getColumn(1).setPreferredWidth(750);
        JTUsu_Exis.getColumnModel().getColumn(1).setResizable(false);
        JTUsu_Exis.getColumnModel().getColumn(2).setPreferredWidth(83);
        JTUsu_Exis.getColumnModel().getColumn(2).setResizable(false);
        JTUsu_Exis.getTableHeader().setReorderingAllowed(false);
        JTUsu_Exis.setAutoResizeMode(JTUsu_Exis.AUTO_RESIZE_OFF);
        JTUsu_Exis.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        
    }
  
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuariosExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuariosExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuariosExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuariosExistentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuariosExistentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBVoltar;
    private javax.swing.JScrollPane JSPUsuario;
    private javax.swing.JTable JTUsu_Exis;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
